export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_IN_LOADING = 'USER_SIGN_IN_LOADING';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_ERROR = 'USER_SIGN_IN_ERROR';

export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_SIGN_UP_LOADING = 'USER_SIGN_UP_LOADING';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_ERROR = 'USER_SIGN_UP_ERROR';