export const GET_ALL_BOOKS = 'GET_ALL_BOOKS';
export const GET_ALL_BOOKS_LOADING = 'GET_ALL_BOOKS_LOADING';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
export const GET_ALL_BOOKS_ERROR = 'GET_ALL_BOOKS_ERROR';